### PR TITLE
Add support for aspectratio extension

### PR DESCRIPTION
**Pull request by TeemuSuoranta**
Here's the aspectratio extension support discussed at https://github.com/16patsle/lazysizes/issues/1

I made this option to be off by default as it adds another js file to load and probably not all users find this extension critical.

### CODE REVIEW

**Comment by 16patsle** [comment]
Looks good! I'll do some testing later, and then merge

**Comment by 16patsle** [comment]
While "later" might have been an understatement, I'm now doing the testing. Hoping to be able to merge this soon.

**Comment by TeemuSuoranta** [comment]
No worries. I have merged a pull request after 1,5 years. Not proud of it, but it has happened.

**Comment by 16patsle** [comment]
Seems to work great, thanks for the PR! I noticed that the Gutenberg editor seems to not add width/height by default, so I'm adding a notice about that. I have some ideas for a workaround, but I'll merge this PR first.

**Pull request merged**
